version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Installing Mocha...
      - npm install -g mocha
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo Running unit tests
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'