kind: Service
apiVersion: v1
metadata:
  name: the-service
spec:
  selector:
    name: the-service
    type: NodePort
    deployment: example-app-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 3000
