kind: Service
apiVersion: v1
metadata:
  name: the-service
spec:
  selector:
    name: the-service
    type: frontend
    deployment: example-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
