variable "cluster_name" {}
variable "instance_type" {}
variable "container_port" {}
variable "container_cpu" {}
variable "container_memory" {}
variable "desired_count" {}
variable "container_name" {}
variable "enable_alb" {}
variable "region" {}
variable "vpc_cidr" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "azs" {}