# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - 'master'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test

  cd: 
    needs: ci
    if: github.ref == 'refs/heads/master' #only run this job for master branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: npm run build --if-present
    - name: Deploy
      run: echo "send stuff to s3"



    

