name: terraform-test
on: [push]
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Init
      id: init
      working-directory: terraform
      run: terraform init
    - name: Terraform Validate
      id: validate
      working-directory: terraform
      run: terraform validate
