name: terraform-test
on: [push]
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Credentials
      run: |
        mkdir -p ~/.config/gcloud
        echo '${{ secrets.GCLOUD_CREDENTIALS }}' > ~/.config/gcloud/application_default_credentials.json
    - name: Terraform Init
      id: init
      working-directory: terraform
      run: terraform init
    - name: Terraform Validate
      id: validate
      working-directory: terraform
      run: terraform validate
    - name: Terraform Plan
      id: plan
      working-directory: terraform
      run: terraform plan
    - name: Terraform Apply
      id: apply
      working-directory: terraform
      run: terraform apply -auto-approve
