name: test-and-deploy
on: [push]
jobs:

  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm test

  terraform-test-and-apply:
    runs-on: ubuntu-latest
    needs:
      - npm-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init
        working-directory: terraform
        run: |
          mkdir -p ~/.config/gcloud
          echo '${{ secrets.GCLOUD_CREDENTIALS }}' > ~/.config/gcloud/application_default_credentials.json
          BRANCH=`echo "$GITHUB_REF" | cut -d/ -f3- | tr / -`
          terraform init
          terraform workspace select $BRANCH
          echo BRANCH=$BRANCH >> $GITHUB_ENV

      - name: Terraform Validate
        id: validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan -var name=${BRANCH} -var git_ref=${GITHUB_SHA}

      - name: Terraform Apply
        id: apply
        working-directory: terraform
        run: terraform apply -auto-approve -var name=${BRANCH} -var git_ref=${GITHUB_SHA} 2>&1
